### ISSUE TITLE
Failed on terraform apply - Quota 'CPUS' exceeded

### ISSUE THREAD

**Issue by mbbroberg** [physIQ/turnkey-riak#1]
I ran into an error during `terraform apply`: 

```
module.riak.google_compute_instance.instance.4: Creation complete
Error applying plan:

7 error(s) occurred:

* google_compute_firewall.ssh: Error creating firewall: googleapi: Error 400: Invalid value for field 'resource.sourceRanges[0]': '64.119.130.146/24'.  Must be a CIDR address range., invalid
* Error running command 'gcloud compute target-pools add-instances bigdata-terraformed-haproxy-target-pool --instances bigdata-terraformed-haproxy-02 --zone us-central1-b': exit status 1. Output: ERROR: (gcloud.compute.target-pools.add-instances) Some requests did not succeed:
 - The resource 'projects/intro-app1/regions/us-central1/targetPools/bigdata-terraformed-haproxy-target-pool' was not found


* Error running command 'gcloud compute target-pools add-instances bigdata-terraformed-haproxy-target-pool --instances bigdata-terraformed-haproxy-01 --zone us-central1-b': exit status 1. Output: ERROR: (gcloud.compute.target-pools.add-instances) Some requests did not succeed:
 - The resource 'projects/intro-app1/regions/us-central1/targetPools/bigdata-terraformed-haproxy-target-pool' was not found


* google_compute_instance.instance.0: Quota 'CPUS' exceeded.  Limit: 8.0

* google_compute_instance.instance.3: Quota 'CPUS' exceeded.  Limit: 8.0

* google_compute_instance.instance.2: Quota 'CPUS' exceeded.  Limit: 8.0

* google_compute_instance.instance.1: Quota 'CPUS' exceeded.  Limit: 8.0


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Running on OS X with the following versions: 

```
$  gcloud version
Google Cloud SDK 0.9.82

bq 2.0.18
bq-nix 2.0.18
core 2015.10.08
core-nix 2015.09.03
gcloud 2015.10.08
gsutil 4.15
gsutil-nix 4.14
$terraform version
Terraform v0.6.4
```

**Comment by cconkright-physiq** [comment]
Good catch. Need to add something in the README about that. Your account has qoutas in place and you are trying to build a cluster that will use to many CPUs. ( there are also disk quotas to check).

I removed those from our accounts, so completely forgot that could happen. You will need to have Google increase your qoutas.

Chad

On Oct 15, 2015 3:52 PM, Matt Brender notifications@github.com wrote:

I ran into an error during terraform apply:

module.riak.google_compute_instance.instance.4: Creation complete
Error applying plan:

7 error(s) occurred:
- google_compute_firewall.ssh: Error creating firewall: googleapi: Error 400: Invalid value for field 'resource.sourceRanges[0]': '64.119.130.146/24'.  Must be a CIDR address range., invalid
- Error running command 'gcloud compute target-pools add-instances bigdata-terraformed-haproxy-target-pool --instances bigdata-terraformed-haproxy-02 --zone us-central1-b': exit status 1. Output: ERROR: (gcloud.compute.target-pools.add-instances) Some requests did not succeed:
  - The resource 'projects/intro-app1/regions/us-central1/targetPools/bigdata-terraformed-haproxy-target-pool' was not found
- Error running command 'gcloud compute target-pools add-instances bigdata-terraformed-haproxy-target-pool --instances bigdata-terraformed-haproxy-01 --zone us-central1-b': exit status 1. Output: ERROR: (gcloud.compute.target-pools.add-instances) Some requests did not succeed:
  - The resource 'projects/intro-app1/regions/us-central1/targetPools/bigdata-terraformed-haproxy-target-pool' was not found
- google_compute_instance.instance.0: Quota 'CPUS' exceeded.  Limit: 8.0
- google_compute_instance.instance.3: Quota 'CPUS' exceeded.  Limit: 8.0
- google_compute_instance.instance.2: Quota 'CPUS' exceeded.  Limit: 8.0
- google_compute_instance.instance.1: Quota 'CPUS' exceeded.  Limit: 8.0

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Running on OS X with the following versions:

$  gcloud version
Google Cloud SDK 0.9.82

bq 2.0.18
bq-nix 2.0.18
core 2015.10.08
core-nix 2015.09.03
gcloud 2015.10.08
gsutil 4.15
gsutil-nix 4.14
$terraform version
Terraform v0.6.4

**Comment by mbbroberg** [comment]
Sounds good @cconkright-physiq - I'll go figure that out and update the README with instructions.

**Comment by mbbroberg** [comment]
Got it. Under Compute > Quotas. I had to upgrade beyond my free account to something with more CPUs. Here we go! :+1:
